name: feat-decoupling
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.5
  - torchvision==0.2.2
  - cudatoolkit=10.0
  - pytorch==1.0.1
  - tqdm
  - matplotlib
  - pandas
  - pip:
    - torchnet